config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :engagements
  resources :groups do
    collection do
      post :import
    end
  end
  resources :users
  root :to => "groups#index"
end

app/models/engagement.rb
class Engagement < ApplicationRecord
  belongs_to :user
  belongs_to :group
  enum role: [:organizer, :participant, :presenter]
  validates :user, uniqueness: { scope: [:group, :role], message: "/Group/Role combination already exists." }

  def stringify
    "User: " + self.user.full_name + ", Group: " + self.group.name + ", Role: " + self.role
  end
end

app/controllers/engagements_controller.rb
class EngagementsController < ApplicationController
  before_action :set_engagement, only: [:show, :edit, :update, :destroy]

  # GET /engagements
  # GET /engagements.json
  def index
    @engagements = Engagement.all
  end

  # GET /engagements/1
  # GET /engagements/1.json
  def show
  end

  # GET /engagements/new
  def new
    @engagement = Engagement.new
    group ||= Group.find_by_id(params[:group])
    if !group
      if Group.first
        group = Group.first
      end
    end
    @engagement.group = group
  end

  # GET /engagements/1/edit
  def edit
  end

  # POST /engagements
  # POST /engagements.json
  def create
    @engagement = Engagement.new(engagement_params)

    respond_to do |format|
      if @engagement.save
        format.html { redirect_to edit_group_path(@engagement.group), notice: 'Engagement was successfully created.' }
        format.json { render :show, status: :created, location: @engagement }
      else
        format.html { render :new }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engagements/1
  # PATCH/PUT /engagements/1.json
  def update
    respond_to do |format|
      if @engagement.update(engagement_params)
        format.html { redirect_to @engagement, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @engagement }
      else
        format.html { render :edit }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engagements/1
  # DELETE /engagements/1.json
  def destroy
    group = @engagement.group
    @engagement.destroy
    respond_to do |format|
      format.html { redirect_to edit_group_path(group), notice: 'Engagement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engagement
      @engagement = Engagement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def engagement_params
      params.require(:engagement).permit(:user_id, :group_id, :role)
    end
end

app/helpers/engagements_helper.rb
module EngagementsHelper
end

app/views/engagements/_form.html.erb
<%= render "shared/errors", resource: @engagement %>

<%= form_for @engagement, html: { class: "well form-horizontal" } do |f| %>
  <fieldset>
    <div class="form-group">
      <label class="col-md-4 control-label">User</label>
      <div class="col-md-8 inputGroupContainer">
        <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.collection_select :user_id, User.order(:last_name), :id, :full_name, { include_blank: false }, {class: "form-control"} %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label">Group</label>
      <div class="col-md-8 inputGroupContainer">
        <div class="input-group"><span class="input-group-addon"><i class="fa fa-users"></i></span>
          <%= f.collection_select :group_id, Group.order(:name), :id, :name, { include_blank: false }, {class: "form-control"} %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label">Role</label>
      <div class="col-md-8 inputGroupContainer">
        <div class="input-group"><span class="input-group-addon"><i class="fa fa-id-badge"></i></span>
          <%= f.select(:role, Engagement.roles.keys.map {|role| [role.titleize,role]}, {:include_blank => false}, {class: "form-control"}) %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-12 inputGroupContainer">
        <div class="input-group pull-right">
          <%= f.submit "Submit", class: "btn btn-success"%>
        </div>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/engagements/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form', engagement: @engagement %>

<%= link_to 'Show', @engagement %> |
<%= link_to 'Back', engagements_path %>

app/views/engagements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Groups</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @engagements.each do |engagement| %>
    <tr>
      <td><%= link_to 'Show', engagement %></td>
      <td><%= link_to 'Edit', edit_engagement_path(engagement) %></td>
      <td><%= link_to 'Destroy', engagement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Group', new_engagement_path %>

app/views/engagements/new.html.erb
<h1>New Engagement</h1>

<%= render 'form', engagement: @engagement %>

<% if @engagement.group  %>
  <%= render "shared/back_button", path: edit_group_path(@engagement.group) %>
<% else %>
  <%= render "shared/back_button", path: new_group_path %>
<% end %>

app/views/engagements/show.html.erb
<h1>Engagement</h1>

<%= render 'form', engagement: @engagement %>

<%= render "shared/back_button", path: edit_group_path(@engagement.group) %>